---
title: "Project title"
subtitle: "Preregistration of analyses"
format: html
editor: visual
execute:
  echo: true
---

# Analysis #1

Describe your first analysis here.

# Analysis #2

In this analysis, we aim to investigate the differences in CO2 production between the first year data was available (1992) and the most recent year data was available (2018) for a certain country. In this analysis, we will perform a Null Hypothesis test where Ho = ğœ‡1 - ğœ‡2 = 0 and HA = ğœ‡1 - ğœ‡2 â‰  0 with the significance level being p \< 0.05 where ğœ‡1 represents the average CO2 emissions for a certain country in 1992 and ğœ‡2 represents the average CO2 emissions of a certain country in 2018. Â The response variable will be CO2 emissions corresponding to the years between 1992 and 2018. We will report the confidence interval and the p-value, as well as include visualizations of the relationship between time and CO2. Regardless of the outcome, we will include the findings in our final report.

\
