---
title: It's Getting Hot in Here
subtitle: Analysis of Global CO2 Emissions Over Time
author: Impressive Squirtle <br> Cassidy Cheesman, Joanne Wang, Ming DeMers, Elisabeth Pan, and Ivan Lin
date: 5/5/23
format: revealjs
editor: visual
execute:
  echo: false
---

## Introduce the topic and motivation

-   Climate change is the biggest challenge facing our generation, with increased global CO2 emissions being one of the leading contributors to this issue.

-   In order to combat the effects of climate change, we must first understand the data behind it.

-   Research questions:

    -   What is the relationship between GDP and CO2 emissions for developing versus developed countries in 2018?

    -   Is the true proportion of countries with a CO2 emission greater than the US in the twentieth century different from those in the twenty-first century?

## Introduce the data

-   Created to show how emissions are changing in each country

-   The Our World in Data team created the original dataset on behalf of the Our World in Data project

-   The instances that comprise the dataset represent countries (per year from 1992 to 2018) with 2484 instances total.

-   The observations (rows) are countries per year and the attributes (columns) are various emission data for each country per year

-   The current dataset we will use is a subset of the original dataset, with all the tonnes units converted into kilotons and the variable names altered

## Highlights from EDA

When you click the **Render** button a presentation will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```

## Inference/modeling/other analysis

Your results here

## Inference/modeling/other analysis

Your results here

## Conclusions + future work
