<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>It’s Getting Hot in Here</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">
 <span class="menu-text">IMPRESSIVE SQUIRTLE</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html">
 <span class="menu-text">Proposal</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./eda.html">
 <span class="menu-text">Exploratory data analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./pre-registration.html">
 <span class="menu-text">Pre-registered analyses</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.html">
 <span class="menu-text">Presentation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" aria-current="page">
 <span class="menu-text">Report</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./appendicies.html">
 <span class="menu-text">Appendicies</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-description" id="toc-data-description" class="nav-link" data-scroll-target="#data-description">Data description</a>
  <ul class="collapse">
  <li><a href="#motivation" id="toc-motivation" class="nav-link" data-scroll-target="#motivation">Motivation</a></li>
  <li><a href="#composition" id="toc-composition" class="nav-link" data-scroll-target="#composition">Composition</a></li>
  <li><a href="#collection-process" id="toc-collection-process" class="nav-link" data-scroll-target="#collection-process">Collection Process</a></li>
  <li><a href="#preprocessingcleaninglabeling" id="toc-preprocessingcleaninglabeling" class="nav-link" data-scroll-target="#preprocessingcleaninglabeling">Preprocessing/cleaning/labeling</a></li>
  </ul></li>
  <li><a href="#data-analysis" id="toc-data-analysis" class="nav-link" data-scroll-target="#data-analysis">Data analysis</a></li>
  <li><a href="#evaluation-of-significance" id="toc-evaluation-of-significance" class="nav-link" data-scroll-target="#evaluation-of-significance">Evaluation of significance</a>
  <ul class="collapse">
  <li><a href="#research-question-one" id="toc-research-question-one" class="nav-link" data-scroll-target="#research-question-one">Research Question One</a></li>
  <li><a href="#research-question-two" id="toc-research-question-two" class="nav-link" data-scroll-target="#research-question-two">Research Question Two</a></li>
  </ul></li>
  <li><a href="#interpretation-and-conclusions" id="toc-interpretation-and-conclusions" class="nav-link" data-scroll-target="#interpretation-and-conclusions">Interpretation and conclusions</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#acknowledgments" id="toc-acknowledgments" class="nav-link" data-scroll-target="#acknowledgments">Acknowledgments</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">It’s Getting Hot in Here</h1>
<p class="subtitle lead">Report</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tibble' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidymodels' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'broom' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dials' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'parsnip' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'recipes' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tune' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'workflowsets' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'yardstick' was built under R version 4.2.3</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 2484 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): Country.Name, Country.Code
dbl (18): Year, Country.GDP, Country.Population, Emissions.Production.CH4, E...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Climate change is the biggest challenge facing our generation, with increased global CO2 emissions being one of the leading contributors to this issue. According to NASA, “Carbon dioxide in the atmosphere warms the planet, causing climate change. Human activities have raised the atmosphere’s carbon dioxide content by 50% in less than 200 years,” and according to Climate.gov, “By adding more carbon dioxide to the atmosphere, people are supercharging the natural greenhouse effect, causing global temperature to rise.” However, in order to combat the effects of climate change, we must first understand the data behind it. In our analysis, we intend to answer the following research questions:</p>
<ol type="1">
<li><p>In 2018, is the true proportion of developed countries with CO2 gas emissions above 1000 kilotons different than those with CO2 gas emissions below 1000 kilotons? The definition of developing versus developed countries will be as defined by the United Nations:</p>
<p>https://www.un.org/en/development/desa/policy/wesp/wesp_current/2014wesp_country_classification.pdf?</p></li>
<li><p>Is the true proportion of countries with a CO2 emission greater than the US in the twentieth century different from those in the twenty-first century?</p></li>
</ol>
<p>Through significance tests we discovered that in 2018, the proportion of industrialized countries with CO2 gas emissions exceeding 1000 kilotons differed from those with CO2 gas emissions below 1000 kilotons, although the data did not provide strong evidence for this claim. The data also offers strong proof that the true fraction of nations with CO2 emissions higher than those of the US in the twentieth century differed from those in the twenty-first.</p>
</section>
<section id="data-description" class="level1">
<h1>Data description</h1>
<section id="motivation" class="level3">
<h3 class="anchored" data-anchor-id="motivation">Motivation</h3>
<p>The dataset was created to show how emissions are changing in each country and allow for comparisons of various countries and regions in relation to overall emission trends along with their sources. The Our World in Data team created the original dataset on behalf of the Our World in Data project, which is a project of the Global Change Data Lab (a non-profit organization based in the United Kingdom). The current dataset we will be using is a subset from the original dataset from the CORGIS Dataset Project created by Sam Donald. The Global Change Data Lab funded the creation of the dataset, and it is a registered charity in England and Wales. Their work is made possible by donations from individuals and organizations that have contributed to their project.</p>
</section>
<section id="composition" class="level3">
<h3 class="anchored" data-anchor-id="composition">Composition</h3>
<p>The dataset’s instances represent countries (per year from 1992 to 2018), and there are 2484 instances in total. The observations (rows) are countries per year, and the attributes (columns) are year, country name, country code, country GDP, country population, emissions production CH4, emissions production N2O, emissions production CO2 cement, emissions production CO2 coal, emissions production CO2 gas, emissions production CO2 oil, emissions production CO2 flaring, emissions production CO2 other, emissions production CO2 total, emissions global share CO2 cement, emissions global share CO2 coal, emissions global share CO2 gas, emissions global share CO2 oil, emissions global share CO2 flaring, emissions global share CO2 total.</p>
</section>
<section id="collection-process" class="level3">
<h3 class="anchored" data-anchor-id="collection-process">Collection Process</h3>
<p>The original dataset is built upon a number of datasets and processing steps. The datasets that were processed include Statistical review of world energy (BP), International energy data (EIA), Primary energy consumption (Our World in Data based on BP’s Statistical review of world energy &amp; EIA’s International energy data), Global carbon budget - Fossil CO2 emissions (Global Carbon Project), Global carbon budget - Global carbon emissions (Global Carbon Project), Global carbon budget - National fossil carbon emissions (Global Carbon Project), Global carbon budget - National land-use change carbon emissions (Global Carbon Project), Global carbon budget (Our World in Data based on the Global Carbon Project’s Fossil CO2 emissions, Global carbon emissions, National fossil carbon emissions, and National land-use change emissions), Greenhouse gas emissions (including methane and nitrous oxide) by sector (CAIT), CO2 dataset (Our World in Data based on all sources above), Population (Our World in Data based on <a href="https://ourworldindata.org/population-sources">a number of different sources</a>), and GDP (University of Groningen GGDC’s Maddison Project Database, Bolt and van Zanden, 2020). The current dataset we are using extracts from the original dataset.</p>
<p>The current dataset we will use depends on the datasets it was built off of and how they were processed, so if certain countries or emission data were left out of those datasets, they will also be left out of our dataset.</p>
</section>
<section id="preprocessingcleaninglabeling" class="level3">
<h3 class="anchored" data-anchor-id="preprocessingcleaninglabeling">Preprocessing/cleaning/labeling</h3>
<p>The various datasets that were the foundation for the original dataset underwent processing steps (the codes of which can be found at this website, https://github.com/owid/co2-data), the names of countries and regions were standardized, the carbon emissions were recalculated to CO2 (e.g.&nbsp;from tonnes of carbon to tonnes of CO2 using a conversion factor of 3.664), and per capita figures were calculated from the dataset’s “Population” metric, which is included in the complete dataset and the population figures were sourced from Gapminder and the UN World Population Prospects (UNWPP). The current dataset we will use is a subset of the original dataset, with all the tonnes units converted into kilotons and the variable names altered.</p>
<p>The link for the software and code that was used to preprocess/clean/label the data: https://github.com/owid/co2-data</p>
</section>
</section>
<section id="data-analysis" class="level1">
<h1>Data analysis</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 92 × 2
   Country.Name          mean
   &lt;chr&gt;                &lt;dbl&gt;
 1 Afghanistan   33132487623.
 2 Albania       21086224119.
 3 Algeria      337419554968.
 4 Angola        80080787153.
 5 Argentina    644263431130.
 6 Armenia       21997234897.
 7 Australia    846270603567.
 8 Austria      306055723842.
 9 Azerbaijan    87440896379.
10 Bangladesh   324340371911.
# ℹ 82 more rows</code></pre>
</div>
</div>
<p>The average GDP for all countries (between 1992 and 2018) in the dataset were calculated and can be found in the displayed tibble.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 92 × 2
   Country.Name    mean
   &lt;chr&gt;          &lt;dbl&gt;
 1 Afghanistan   0.308 
 2 Albania       0.0591
 3 Algeria      54.3   
 4 Angola        1.21  
 5 Argentina    76.1   
 6 Armenia       3.19  
 7 Australia    56.1   
 8 Austria      16.3   
 9 Azerbaijan   17.6   
10 Bangladesh   28.6   
# ℹ 82 more rows</code></pre>
</div>
</div>
<p>The average CO2 gas emissions for all countries (between 1992 and 2018) in the dataset were calculated and can be found in the second displayed tibble.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/eda-gdp-developed-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/eda-gdp-developed-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/eda-gdp-developing-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/eda-gdp-developing-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Through visualizing the change in GDP over time for the two developed (United States and Japan) countries and the two developing countries (Pakistan and Vietnam), it can be seen that it appears that developing countries have a much higher rate of increase in GDP over time than developed countries do. However, as expected, the developing countries have much lower GDPs than developed countries in general.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/eda-co2-developed-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/eda-co2-developed-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/eda-co2-developing-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/eda-co2-developing-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Through visualizing the change in CO2 gas emissions over time for the two developed (United States and Japan) countries and the two developing countries (Pakistan and Vietnam), it can be seen that it appears that developing countries have a much higher rate of increase in CO2 gas emissions over time than developed countries do. Furthermore, as expected, despite higher rates of growth in CO2 gas emissions over time for developing countries, developed countries tend to have much higher CO2 gas emissions overall than developing countries.</p>
<p>The above observations could indicate a possible correlation between GDP growth and increased CO2 emissions. It could also suggest that developed countries produce much more CO2 gas than developing countries, contributing much more to climate change, but that there is an upward trend in development in developing countries that are also increasing CO2 gas emissions.</p>
<p>We will utilize a logistic regression model to analyze the relationship between GDP and CO2 gas emissions for developing versus developed countries in 2018. As there is no clear definition of a GDP threshold that determines whether a country is developed or developing, we will use the United Nations’ definition (https://www.un.org/en/development/desa/policy/wesp/wesp_current/2014wesp_country_classification.pdf?), since their definition takes a country’s GDP into account.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term                          estimate std.error statistic p.value
  &lt;chr&gt;                            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)                   0.573      0.232       2.46   0.0137
2 Emissions.Production.CO2.Gas -0.000483   0.00105    -0.460  0.645 </code></pre>
</div>
</div>
<p>The logistic regression model using the total CO2 emissions production as an explanatory variable is as follows:</p>
<p><span class="math display">\[
log(\frac{p}{1-p})= 0.573 - 0.000483 \times CO2~gas~emissions
\]</span></p>
<p>The probability a country is developed can be calculated as:</p>
<p><span class="math display">\[p = \frac{\exp\{0.573 - 0.000483 \times CO2~gas~emissions\}}{1 + \exp\{0.573 - 0.000483 \times CO2~gas~emissions\}}\]</span></p>
<p>Thus, using the logistic regression model, if the CO2 gas emissions of a given country is 100 kilotons, the probability that that country is developed is 0.37:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  .pred_developed .pred_developing
            &lt;dbl&gt;            &lt;dbl&gt;
1           0.372            0.628</code></pre>
</div>
</div>
<p>If the CO2 gas emissions of a given country is 1000 kilotons, the probability that that country is developed is 0.48:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  .pred_developed .pred_developing
            &lt;dbl&gt;            &lt;dbl&gt;
1           0.478            0.522</code></pre>
</div>
</div>
<p>If the CO2 gas emissions of a given country is 3000 kilotons, the probability that that country is developed is 0.71:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  .pred_developed .pred_developing
            &lt;dbl&gt;            &lt;dbl&gt;
1           0.706            0.294</code></pre>
</div>
</div>
<p>Using the default decision-making threshold of 0.5 (that is, if the predicted probability that a country is developed is greater than 0.5, then we would classify it as developed), we can see that as the CO2 gas emissions increases, the probability that the country is developed also increases, which indicates that GDP growth/higher GDP is correlated with higher CO2 gas emissions. Additionally, it appears that there is a CO2 gas emission threshold of around 1000 kilotons, where countries with CO2 gas emissions greater than 1000 kilotons are most likely developed, while countries with CO2 gas emissions less than 1000 kilotons are most likely developing.</p>
</section>
<section id="evaluation-of-significance" class="level1">
<h1>Evaluation of significance</h1>
<section id="research-question-one" class="level2">
<h2 class="anchored" data-anchor-id="research-question-one">Research Question One</h2>
<p>The first research question we will attempt to answer is: In 2018, is the true proportion of developed countries with CO2 gas emissions above 1000 kilotons different than those with CO2 gas emissions below 1000 kilotons? As there is no clear definition of a GDP threshold determining whether a country is developed or developing, we will again use the United Nations’ definition (https://www.un.org/en/development/desa/policy/wesp/wesp_current/2014wesp_country_classification.pdf?), since their definition takes a country’s GDP into account. To answer this question, we will conduct a hypothesis test.</p>
<p>Using the observed potential CO2 gas emission threshold of around 1000 kilotons from the logistic regression model, the null hypothesis is that in 2018, the true proportion of developed countries with CO2 gas emissions above 1000 kilotons is not different than those with CO2 gas emissions below 1000 kilotons. The alternative hypothesis is that in 2018, the true proportion of developed countries with CO2 gas emissions above 1000 kilotons is different than those with CO2 gas emissions below 1000 kilotons. In proper notation:</p>
<p><span class="math display">\[ H_0 : p_a - p_b = 0 \]</span> <span class="math display">\[ H_A: p_a - p_b \neq 0 \]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  p_value
    &lt;dbl&gt;
1   0.766</code></pre>
</div>
</div>
<p>Since the p-value is 0.766, which is greater than the significance level of 0.05, we fail to reject the null hypothesis. The data fails to provide convincing evidence that in 2018, the proportion of developed countries with CO2 gas emissions above 1000 kilotons is different from those with CO2 gas emissions below 1000 kilotons.</p>
</section>
<section id="research-question-two" class="level2">
<h2 class="anchored" data-anchor-id="research-question-two">Research Question Two</h2>
<p>The second research question we will attempt to answer is if the true proportion of countries with a CO2 emission greater than the US in the twentieth century is different from those in the twenty-first century. We will do this using a null hypothesis test. The null hypothesis is that there is no difference between the centuries, and the alternative hypothesis is the opposite: that there is a difference. In proper notation:</p>
<p><span class="math display">\[
H_0 : p_a - p_b = 0
\]</span> <span class="math display">\[
H_A: p_a - p_b \neq 0
\]</span></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/research-question-two-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Please be cautious in reporting a p-value of 0. This result is an
approximation based on the number of `reps` chosen in the `generate()` step.
See `?get_p_value()` for more information.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  p_value
    &lt;dbl&gt;
1       0</code></pre>
</div>
</div>
<p>Since the p-value is 0, which is less than the significance level of 0.05, we reject the null hypothesis in favor of the alternative hypothesis. The data provide convincing evidence that the true proportion of countries with a CO2 emission greater than the US in the twentieth century differs from those in the twenty-first century.</p>
</section>
</section>
<section id="interpretation-and-conclusions" class="level1">
<h1>Interpretation and conclusions</h1>
<p>We investigate the CO2 emissions of the world and its nations from 1992 - 2018. First, we create some graphs using the UN definition of developing/developed nations. Through our visualizations, GDP change over time for developing countries is increasing, but much faster than in developed countries. The same is for CO2 emissions, where both developed types of nations have increasing emissions. Still, developing nations have a much higher rate of increase (although developed countries have much higher emissions than developing nations in the first place). We found, with a logistic regression, that as a country’s carbon emissions increase, the more likely it was developed.</p>
<p>We thus conducted a correlation test to see if the CO2 increase was steeper in developing or developed nations. However, the data and test statistics showed us that it was unlikely that there was a difference in proportion between developed countries with CO2 gas emissions above 1,000 kilotons and nations with emissions less than 1,000 kilotons.</p>
<p>Secondly, we investigate if the true proportion of nations with CO2 emissions greater than the US in the 20th century is different than those in the 21st century. In our 2-proportion test, there is indeed a likelihood that the proportion of nations with higher carbon emissions than the US is different between the two centuries.</p>
<p>We find that there is indeed an increase in CO2 emissions and that this increase is correlated to a country’s GDP. Furthermore, our data indicate a dramatic rise in CO2 emissions; for developing countries, a near-exponential increase, and for developed countries, a linear increase.</p>
<p>Regardless, according to the United Nations Environment Program (UNEP) and the Environmental Protection Agency (EPA), Carbon dioxide emissions are problematic because they contribute to the warming of the Earth’s atmosphere and the subsequent climate change. Furthermore, in developing nations, we tend to see industrialization, which means more burning of fossil fuels and deforestation, thus increasing CO2 emissions. Therefore, we see an increase in emissions from these countries.</p>
<p>Reducing emissions is essential to mitigate the impacts of climate change and limit the ever-increasing global temperature. This requires transitioning to renewable energy sources, improving energy efficiency, reducing deforestation, and promoting reforestation and eco-repair. Developing or developed, every nation has a duty to help protect and preserve the planet in which we all reside.</p>
</section>
<section id="limitations" class="level1">
<h1>Limitations</h1>
<ul>
<li><p>Not all 195 countries are in our dataset, which limits the scope of our dataset a bit.</p></li>
<li><p>The years within the dataset only range from 1992 to 2018, which could be a limitation because the range is 26 years, which may or may not be a long enough time period to see substantive changes in GDP or CO2 emissions. Additionally, this dataset does not contain data for more recent years, which could be another limitation if we want to see the most up-to-date data on GDP/emissions for different countries.</p></li>
<li><p>We wanted to see the relationship between GDP and CO2 emissions for developed and developing countries, however, there was no exact GDP threshold to determine if a country is developed or not. Thus, we used the UN classification which takes GDP into account, but GDP is not the sole determining factor of whether a country is developing or not.</p></li>
</ul>
</section>
<section id="acknowledgments" class="level1">
<h1>Acknowledgments</h1>
<p>We would first like to express our sincere thanks to our section’s graduate TA that has helped us every step of the way: Chi-Jung L. We would also like to acknowledge our peer reviewers Impressive Charmander and Impressive Togepi, who have provided us with constructive feedback to better our projects. We want to thank Professor Benjamin Soltoff for all the helpful AEs he walked us through. Lastly, we would like to acknowledge the Our World Our Data team for the report’s dataset. Our report would not have been possible without the assistance of all those mentioned above.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>